# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entry_meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entry_meta.proto',
  package='mit.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x65ntry_meta.proto\x12\x0cmit.protobuf\"&\n\x0c\x46ieldIdArray\x12\x16\n\x0e\x66ield_id_array\x18\x01 \x03(\r\"\xc6\x01\n\tEntryMeta\x12\x41\n\x0e\x65ntry_meta_map\x18\x01 \x03(\x0b\x32).mit.protobuf.EntryMeta.EntryMetaMapEntry\x12\x16\n\x0e\x65mbedding_size\x18\x02 \x01(\r\x12\r\n\x05model\x18\x03 \x01(\t\x1aO\n\x11\x45ntryMetaMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.mit.protobuf.FieldIdArray:\x02\x38\x01\x42)\n\x11org.openmit.entryB\x0f\x45ntryMetaProtosP\x01\xf8\x01\x01\x62\x06proto3')
)




_FIELDIDARRAY = _descriptor.Descriptor(
  name='FieldIdArray',
  full_name='mit.protobuf.FieldIdArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_id_array', full_name='mit.protobuf.FieldIdArray.field_id_array', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=72,
)


_ENTRYMETA_ENTRYMETAMAPENTRY = _descriptor.Descriptor(
  name='EntryMetaMapEntry',
  full_name='mit.protobuf.EntryMeta.EntryMetaMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mit.protobuf.EntryMeta.EntryMetaMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mit.protobuf.EntryMeta.EntryMetaMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=273,
)

_ENTRYMETA = _descriptor.Descriptor(
  name='EntryMeta',
  full_name='mit.protobuf.EntryMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_meta_map', full_name='mit.protobuf.EntryMeta.entry_meta_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embedding_size', full_name='mit.protobuf.EntryMeta.embedding_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='mit.protobuf.EntryMeta.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENTRYMETA_ENTRYMETAMAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=273,
)

_ENTRYMETA_ENTRYMETAMAPENTRY.fields_by_name['value'].message_type = _FIELDIDARRAY
_ENTRYMETA_ENTRYMETAMAPENTRY.containing_type = _ENTRYMETA
_ENTRYMETA.fields_by_name['entry_meta_map'].message_type = _ENTRYMETA_ENTRYMETAMAPENTRY
DESCRIPTOR.message_types_by_name['FieldIdArray'] = _FIELDIDARRAY
DESCRIPTOR.message_types_by_name['EntryMeta'] = _ENTRYMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldIdArray = _reflection.GeneratedProtocolMessageType('FieldIdArray', (_message.Message,), dict(
  DESCRIPTOR = _FIELDIDARRAY,
  __module__ = 'entry_meta_pb2'
  # @@protoc_insertion_point(class_scope:mit.protobuf.FieldIdArray)
  ))
_sym_db.RegisterMessage(FieldIdArray)

EntryMeta = _reflection.GeneratedProtocolMessageType('EntryMeta', (_message.Message,), dict(

  EntryMetaMapEntry = _reflection.GeneratedProtocolMessageType('EntryMetaMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _ENTRYMETA_ENTRYMETAMAPENTRY,
    __module__ = 'entry_meta_pb2'
    # @@protoc_insertion_point(class_scope:mit.protobuf.EntryMeta.EntryMetaMapEntry)
    ))
  ,
  DESCRIPTOR = _ENTRYMETA,
  __module__ = 'entry_meta_pb2'
  # @@protoc_insertion_point(class_scope:mit.protobuf.EntryMeta)
  ))
_sym_db.RegisterMessage(EntryMeta)
_sym_db.RegisterMessage(EntryMeta.EntryMetaMapEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021org.openmit.entryB\017EntryMetaProtosP\001\370\001\001'))
_ENTRYMETA_ENTRYMETAMAPENTRY.has_options = True
_ENTRYMETA_ENTRYMETAMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
