// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entry_meta.proto

package org.openmit.entry;

public final class EntryMetaProtos {
  private EntryMetaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mit_protobuf_FieldIdArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mit_protobuf_FieldIdArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mit_protobuf_EntryMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mit_protobuf_EntryMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mit_protobuf_EntryMeta_EntryMetaMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mit_protobuf_EntryMeta_EntryMetaMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020entry_meta.proto\022\014mit.protobuf\"&\n\014Fiel" +
      "dIdArray\022\026\n\016field_id_array\030\001 \003(\r\"\306\001\n\tEnt" +
      "ryMeta\022A\n\016entry_meta_map\030\001 \003(\0132).mit.pro" +
      "tobuf.EntryMeta.EntryMetaMapEntry\022\026\n\016emb" +
      "edding_size\030\002 \001(\r\022\r\n\005model\030\003 \001(\t\032O\n\021Entr" +
      "yMetaMapEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(" +
      "\0132\032.mit.protobuf.FieldIdArray:\0028\001B)\n\021org" +
      ".openmit.entryB\017EntryMetaProtosP\001\370\001\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mit_protobuf_FieldIdArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mit_protobuf_FieldIdArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mit_protobuf_FieldIdArray_descriptor,
        new java.lang.String[] { "FieldIdArray", });
    internal_static_mit_protobuf_EntryMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mit_protobuf_EntryMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mit_protobuf_EntryMeta_descriptor,
        new java.lang.String[] { "EntryMetaMap", "EmbeddingSize", "Model", });
    internal_static_mit_protobuf_EntryMeta_EntryMetaMapEntry_descriptor =
      internal_static_mit_protobuf_EntryMeta_descriptor.getNestedTypes().get(0);
    internal_static_mit_protobuf_EntryMeta_EntryMetaMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mit_protobuf_EntryMeta_EntryMetaMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
