// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entry_meta.proto

package org.openmit.entry;

/**
 * Protobuf type {@code mit.protobuf.FieldIdArray}
 */
public  final class FieldIdArray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mit.protobuf.FieldIdArray)
    FieldIdArrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldIdArray.newBuilder() to construct.
  private FieldIdArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldIdArray() {
    fieldIdArray_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldIdArray(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              fieldIdArray_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            fieldIdArray_.add(input.readUInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              fieldIdArray_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              fieldIdArray_.add(input.readUInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        fieldIdArray_ = java.util.Collections.unmodifiableList(fieldIdArray_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmit.entry.EntryMetaProtos.internal_static_mit_protobuf_FieldIdArray_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmit.entry.EntryMetaProtos.internal_static_mit_protobuf_FieldIdArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmit.entry.FieldIdArray.class, org.openmit.entry.FieldIdArray.Builder.class);
  }

  public static final int FIELD_ID_ARRAY_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> fieldIdArray_;
  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getFieldIdArrayList() {
    return fieldIdArray_;
  }
  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  public int getFieldIdArrayCount() {
    return fieldIdArray_.size();
  }
  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  public int getFieldIdArray(int index) {
    return fieldIdArray_.get(index);
  }
  private int fieldIdArrayMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getFieldIdArrayList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(fieldIdArrayMemoizedSerializedSize);
    }
    for (int i = 0; i < fieldIdArray_.size(); i++) {
      output.writeUInt32NoTag(fieldIdArray_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < fieldIdArray_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(fieldIdArray_.get(i));
      }
      size += dataSize;
      if (!getFieldIdArrayList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      fieldIdArrayMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmit.entry.FieldIdArray)) {
      return super.equals(obj);
    }
    org.openmit.entry.FieldIdArray other = (org.openmit.entry.FieldIdArray) obj;

    boolean result = true;
    result = result && getFieldIdArrayList()
        .equals(other.getFieldIdArrayList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFieldIdArrayCount() > 0) {
      hash = (37 * hash) + FIELD_ID_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getFieldIdArrayList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmit.entry.FieldIdArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.FieldIdArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.openmit.entry.FieldIdArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.FieldIdArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmit.entry.FieldIdArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mit.protobuf.FieldIdArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mit.protobuf.FieldIdArray)
      org.openmit.entry.FieldIdArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmit.entry.EntryMetaProtos.internal_static_mit_protobuf_FieldIdArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmit.entry.EntryMetaProtos.internal_static_mit_protobuf_FieldIdArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmit.entry.FieldIdArray.class, org.openmit.entry.FieldIdArray.Builder.class);
    }

    // Construct using org.openmit.entry.FieldIdArray.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fieldIdArray_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmit.entry.EntryMetaProtos.internal_static_mit_protobuf_FieldIdArray_descriptor;
    }

    public org.openmit.entry.FieldIdArray getDefaultInstanceForType() {
      return org.openmit.entry.FieldIdArray.getDefaultInstance();
    }

    public org.openmit.entry.FieldIdArray build() {
      org.openmit.entry.FieldIdArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.openmit.entry.FieldIdArray buildPartial() {
      org.openmit.entry.FieldIdArray result = new org.openmit.entry.FieldIdArray(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        fieldIdArray_ = java.util.Collections.unmodifiableList(fieldIdArray_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.fieldIdArray_ = fieldIdArray_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmit.entry.FieldIdArray) {
        return mergeFrom((org.openmit.entry.FieldIdArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmit.entry.FieldIdArray other) {
      if (other == org.openmit.entry.FieldIdArray.getDefaultInstance()) return this;
      if (!other.fieldIdArray_.isEmpty()) {
        if (fieldIdArray_.isEmpty()) {
          fieldIdArray_ = other.fieldIdArray_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFieldIdArrayIsMutable();
          fieldIdArray_.addAll(other.fieldIdArray_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.openmit.entry.FieldIdArray parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.openmit.entry.FieldIdArray) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> fieldIdArray_ = java.util.Collections.emptyList();
    private void ensureFieldIdArrayIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        fieldIdArray_ = new java.util.ArrayList<java.lang.Integer>(fieldIdArray_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getFieldIdArrayList() {
      return java.util.Collections.unmodifiableList(fieldIdArray_);
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public int getFieldIdArrayCount() {
      return fieldIdArray_.size();
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public int getFieldIdArray(int index) {
      return fieldIdArray_.get(index);
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public Builder setFieldIdArray(
        int index, int value) {
      ensureFieldIdArrayIsMutable();
      fieldIdArray_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public Builder addFieldIdArray(int value) {
      ensureFieldIdArrayIsMutable();
      fieldIdArray_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public Builder addAllFieldIdArray(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureFieldIdArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fieldIdArray_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Lists of id for field 
     * </pre>
     *
     * <code>repeated uint32 field_id_array = 1;</code>
     */
    public Builder clearFieldIdArray() {
      fieldIdArray_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mit.protobuf.FieldIdArray)
  }

  // @@protoc_insertion_point(class_scope:mit.protobuf.FieldIdArray)
  private static final org.openmit.entry.FieldIdArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmit.entry.FieldIdArray();
  }

  public static org.openmit.entry.FieldIdArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldIdArray>
      PARSER = new com.google.protobuf.AbstractParser<FieldIdArray>() {
    public FieldIdArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldIdArray(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldIdArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldIdArray> getParserForType() {
    return PARSER;
  }

  public org.openmit.entry.FieldIdArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

