// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entry_meta.proto

package org.openmit.entry;

public interface FieldIdArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mit.protobuf.FieldIdArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  java.util.List<java.lang.Integer> getFieldIdArrayList();
  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  int getFieldIdArrayCount();
  /**
   * <pre>
   * Lists of id for field 
   * </pre>
   *
   * <code>repeated uint32 field_id_array = 1;</code>
   */
  int getFieldIdArray(int index);
}
