#ifndef OPENMIT_FRAMEWORK_PS_SIGNAL_H_
#define OPENMIT_FRAMEWORK_PS_SIGNAL_H_

namespace mit {
namespace signal {
/*! \brief */
enum CommSignals {
  // signals generated by worker
  WORKER_COMPLETE,
  WORKER_EPOCH_COMPLETE,
  UPDATE,
  SAVEINFO,
  SAVEMODEL,
  METRIC,
  FINISH,
  // signals generated by server
  SERVER_COMPLETE,
  // signals generated by scheduler
  EARLY_STOP
};

} // namespace ps
} // namespace mit

#endif // OPENMIT_FRAMEWORK_PS_SIGNAL_H_
